on:
  push:
      branches: [ main ]

name: Build and Deploy
env:
  PROJECT_ID: "oidc-demo-373615"
  PROJECT_NUMBER: "172014898938"
  REGION: "us-east1"
  SERVICE_ACCOUNT: "workflows-sa@oidc-demo-373615.iam.gserviceaccount.com"

jobs:
  Build:
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.3.1'
      with:
        create_credentials_file: 'true'
        workload_identity_provider: projects/172014898938/locations/global/workloadIdentityPools/github-pool2/providers/github-provider2
        service_account: workflows-sa@oidc-demo-373615.iam.gserviceaccount.com

    # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    # Build and Push Container
    - name: Build and Push Container to artifact registry
      run: |-
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud auth list
        gcloud builds submit ./cool-security-api/ --tag ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/cool-security-api/cool-api:${{  github.sha }} --project oidc-demo-373615 
